import { Inter } from 'next/font/google'
import { Lexend_Deca } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const lex = Lexend_Deca({
  weight: ['200','300','400', '500', '600', '700', '800', '900'] ,
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Reeco',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={lex.className}>{children}</body>
    </html>
  )
}
